# @name signup

POST http://localhost:3003/users/signup
Content-Type: application/json

{
   "name": "Adamastor", 
   "email": "cookenuser1@email.com",
   "password": "123456",
   "role": "ADMIN"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmM2Y0YzUxLTFjMWMtNGFhZi04NDYwLTQ5YTNlYzU2MGM3MSIsImlhdCI6MTY2Mjk5OTQ2MywiZXhwIjoxNjYzMDg1ODYzfQ.FAvX1OOxTqZN-gzC-ErS0Gb3ru0ZMBYGOWXCF9q7OpE
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyNDI5MTQyLTcxYTctNGZmYS05ZTM1LTIzYWMxYWQ1ZDM5YyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MzI5NjQ3NywiZXhwIjoxNjY1ODg4NDc3fQ.Gv98I36S-wggMP7R8GwuO1-7wBuHwFEJtQUKtUXIsGM

###
GET http://localhost:3003/users/profile
Authorization{{tokenAdmin}}

###
PUT http://localhost:3003/user/edit
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
   "name": "Bruno Amorim" 
}

###
POST http://localhost:3003/users/login
Content-Type: application/json

{
   "email":"cookenuadmin@email.com",
   "password":"123456" 
}
