### 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Aline",
    "email": "aline@gmail.com",
    "password": "abc123"
}

###
# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

###
POST http://localhost:3003/posts/create-post
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
   "content": "mais um, só pra testar"
}

###
GET http://localhost:3003/posts/get-post
Authorization: {{login.response.body.token}}