### 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Aline",
    "email": "aline@gmail.com",
    "password": "abc123"
}

###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

###
POST 