###
post http://localhost:3003/users
Content-Type: application/json

{
    "name": "Pedro",
    "email": "pedro@gmail.com",
    "password":"123456p"

}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Mouse Gamer",
    "price": "45.00",
    "image_url":"https://a-static.mlcdn.com.br/800x560/mouse-gamer-evolut-eg-104-rgb-led-rayden-2400-dpi-6-botoes/bornarkitel1/63/2112dae6567e9f54b02bd5ccf9f74"

}

###
GET http://localhost:3003/products