###
post http://localhost:3003/users
Content-Type: application/json

{
    "name": "Pedro",
    "email": "pedro@gmail.com",
    "password":"123456p"

}

###
GET http://localhost:3003/users


###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Monitor Gamer Curvo Samsung Odyssey 27",
    "price": "4599.00",
    "image_url":"https://images.samsung.com/is/image/samsung/br-odyssey-g7-c27g75t-lc27g75tqslxzd--308174086?$1300_1038_PNG$"

}
